---
name: "release-please"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      major: ${{ steps.release-please.outputs.major }}
      minor: ${{ steps.release-please.outputs.minor }}
      patch: ${{ steps.release-please.outputs.patch }}
    steps:
      - name: Generate authentication token from GitHub App
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.REPOSITORY_BOT_APP_ID }}
          private-key: ${{ secrets.REPOSITORY_BOT_PRIVATE_KEY }}

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}

  upload-release-artifact:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    steps:
      - name: "Check out the repository"
        if: ${{ needs.release-please.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: "Setup Java and Maven"
        if: ${{ needs.release-please.outputs.releases_created }}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: "Package JAR using Maven wrapper"
        if: ${{ needs.release-please.outputs.releases_created }}
        run: ./mvnw dependency:go-offline clean compile package

      - name: "Upload Release Artifact"
        if: ${{ needs.release-please.outputs.releases_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} ./target/gpg-keyserver-${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}.jar
